#!/bin/bash

###########- COLOR CODE -##############
NC="\e[0m"
green="\033[0;32m"
red="\033[0;31m"
###########- END COLOR CODE -##########

clear
grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq | nl
echo ""
read -rp "➥ Input Username : " user
sleep 0.5
exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
clear
systemctl restart xray
echo -e "------------------------------------------------------"
echo -e " ❏ 𝐃𝐞𝐥𝐞𝐭𝐞 𝐕𝐦𝐞𝐬𝐬 𝐀𝐜𝐜𝐨𝐮𝐧𝐭"
echo -e " ❏ 𝖠𝖼𝖼𝗈𝗎𝗇𝗍 𝚁𝚎𝚖𝚘𝚟𝚎 𝚂𝚞𝚌𝚌𝚎𝚜𝚜𝚏𝚞𝚕𝚕𝚢"
echo -e "------------------------------------------------------"
echo -e ""
echo -e " ❖ Username   : $user"
echo -e "------------------------------------------------------"