#!/bin/bash

source /etc/os-release
sp=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
ct=$(curl -s ipinfo.io/city )
IPVPS=$(curl -s ipinfo.io/ip )
d1=$(date -d "$exp" +%s)
d2=$(date -d "$today" +%s)
useram=$( free -m | awk 'NR==2 {print $3}' )
totalram=$( free -m | awk 'NR==2 {print $2}' )
domain=$(cat /etc/xray/domain)
ssh=$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)
trojanws=$(grep -E "^### " "/etc/trojan-go/akun.conf" | cut -d ' ' -f 2-3 | sort | uniq | wc -l)
vmess=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | wc -l)
vless=$(grep -E "^#&&# " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | wc -l)
uptimesvr="$(uptime -p | cut -d " " -f 2-10)"

# Mendapatkan jam saat ini
hour=$(date +"%H")

# Menentukan ucapan berdasarkan waktu
if [ "$hour" -ge 5 ] && [ "$hour" -lt 10 ]; then
    greeting="𝑺𝒆𝒍𝒂𝒎𝒂𝒕 𝒑𝒂𝒈𝒊 🌄"
elif [ "$hour" -ge 10 ] && [ "$hour" -lt 15 ]; then
    greeting="𝑺𝒆𝒍𝒂𝒎𝒂𝒕 𝒔𝒊𝒂𝒏𝒈 🌤️"
elif [ "$hour" -ge 15 ] && [ "$hour" -lt 20 ]; then
    greeting="𝑺𝒆𝒍𝒂𝒎𝒂𝒕 𝒔𝒐𝒓𝒆 🌇"
else
    greeting="𝑺𝒆𝒍𝒂𝒎𝒂𝒕 𝒎𝒂𝒍𝒂𝒎 🌙"
fi

# Mendapatkan uptime sistem
uptime_info=$(uptime -p)

echo "━━━━━━━━━━━━━━━━━━━━━━━"
echo " 𝓗𝓪𝓵𝓵𝓸 𝓑𝓸𝓼 👋, $greeting"
echo "━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏲️ Jam saat ini: $(date '+%H:%M:%S')"
echo "📅 Hari saat ini: $(date '+%A, %d %B %Y')"
echo "━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏠 𝐓𝐨𝐭𝐚𝐥 𝐚𝐤𝐮𝐧 𝐲𝐚𝐧𝐠 𝐛𝐞𝐫𝐡𝐚𝐬𝐢𝐥 𝐝𝐢𝐛𝐮𝐚𝐭."
echo ""
echo "⚡ 𝚂𝚂𝙷 𝚆𝚂 + 𝚄𝙳𝙿 : $ssh 𝙰𝚌𝚌𝚘𝚞𝚗𝚝"
echo "⚡ 𝚇𝚛𝚊𝚢 𝚅𝚖𝚎𝚜𝚜  : $vmess 𝙰𝚌𝚌𝚘𝚞𝚗𝚝"
echo "⚡ 𝚇𝚛𝚊𝚢 𝚅𝚕𝚎𝚜𝚜  : $vless 𝙰𝚌𝚌𝚘𝚞𝚗𝚝"
echo "⚡ 𝚇𝚛𝚊𝚢 𝚃𝚛𝚘𝚓𝚊𝚗 : $trojanws 𝙰𝚌𝚌𝚘𝚞𝚗𝚝"
echo "━━━━━━━━━━━━━━━━━━━━━━━"
echo "Built by @SaputraTech"
echo "Status : Admin Access"
echo "Bot Uptime : $uptime_info"
echo "Bot Version 1.0.23 "